### ISSUE TITLE
Number of countries visited

### ISSUE THREAD

**Issue by JohannesBuchner** [christianhaller/download-your-travelmap#1]
Hi,

Great tool! Could you add a simple feature that all the users on that forum are asking for -- counting the number of countries visited.

I think it should be quite simple to implement given the CSV file: Split city name by its comma. Place the second part (the country) in a set. Count the number of unique items in the set. Display it as a fat text above or below the map.

The number of cities is simply the number of items in the CSV file, not sure about the "percent of the world traveled", that is of course more ambiguous -- but it could just be number of countries visited divided by total number of countries (~193).

Cheers,
             Johannes

**Comment by christianhaller** [comment]
Hi Johannes, thanks for your cool feaure request! :)
In this beta you can see your stats https://travelmap.s3.amazonaws.com/index.html

It's part of a huge rewrite (from php to nodejs), so it needs a couple of days for going live.

**Comment by christianhaller** [comment]
And it's online :)

http://download-your-travelmap.christianhaller.com/

**Comment by JohannesBuchner** [comment]
yay!
