### ISSUE TITLE
Error message: Internal server error

### ISSUE THREAD

**Issue by msummers40** [christianhaller/download-your-travelmap#29]
Hi @christianhaller 

Thank you for building this tool. I tried using it in Chrome and Safari on my Mac and, well, it's not working.

In Chrome, things hang up at this point:
![image](https://cloud.githubusercontent.com/assets/5499606/14586812/7c882a5c-049c-11e6-9b6f-523ad4efd9c6.png)

In Safari, I receive this error message:

![image](https://cloud.githubusercontent.com/assets/5499606/14586825/bcdbdd60-049c-11e6-8893-496940746995.png)

I receive the same result/message when I use the http and https versions of my page:
https://www.tripadvisor.com/members/msummers40

**Comment by christianhaller** [comment]
Hi @msummers40 
thanks for your bug report.
I think, I misconfigured AWS Gateway API some days ago.
It should be fixed now :)
https://download-your-travelmap.christianhaller.com/?url=https://www.tripadvisor.com/members/msummers40

**Comment by msummers40** [comment]
Perfect. Thank you!
