### ISSUE TITLE
% of world traveled

### ISSUE THREAD

**Issue by JohannesBuchner** [christianhaller/download-your-travelmap#5]
So someone came up with the idea to measure how much of a world traveler one is using the Risk map:

http://www.atlasandboots.com/what-qualifies-travel-world/

This might be a nice feature and give a more reliable percentage.

Implementationwise one could assign each actual country to a Risk territory, and then just count the number of unique territories visited.

**Comment by christianhaller** [comment]
Hi @JohannesBuchner, that's a cool idea. I like it very much :+1: 

So this map 
https://en.wikipedia.org/wiki/File:Risk_game_map_fixed.png
and this data
https://github.com/christianhaller/download-your-travelmap/blob/master/backend/iso/index.js
have to be combined?

**Comment by JohannesBuchner** [comment]
pretty much.

The US, Canada and Australia have to be split, unfortunately, and the splits do not look trivial.

Here is a clean map
http://bloge.p-gis.com/2012/02/adding-labels-to-arcgis-online-web-maps.html
It is in Web Mercator projection https://en.wikipedia.org/wiki/Web_Mercator
(you can ignore the first term up including the zoom level as they are constants).

I think it might be easier to make a polygon for each territory (e.g. fetch pixel coordinates with with gimp). Then for each visited city, project the lat/lon onto Web Mercator, check if inside polygon (https://en.wikipedia.org/wiki/Point_in_polygon) -> mark that territory as visited.

**Comment by christianhaller** [comment]
I found some more helpful links:

a good svg map:
https://upload.wikimedia.org/wikipedia/commons/1/14/Mercator_Projection.svg

some math:
https://developers.google.com/maps/documentation/javascript/examples/map-coordinates

but I'm still looking for territory coordinates.

**Comment by christianhaller** [comment]
Oh, this looks good http://dartlangfr-risk.herokuapp.com/

**Comment by christianhaller** [comment]
https://en.wikipedia.org/wiki/File:Riskgameboard.svg
